apiVersion: v1
kind: Service
metadata:
  name: app-blue-svc
spec:
  selector:
    app: myapp
    version: blue
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-green-svc
spec:
  selector:
    app: myapp
    version: green
  ports:
  - port: 80
    targetPort: 80